# Copyright 2020-2022 Signal Messenger, LLC
# SPDX-License-Identifier: AGPL-3.0-only

name: Benchmark
on:
  push:
    branches:
      - development
      - main
      - '[0-9]+.[0-9]+.x'
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'signalapp/Signal-Desktop-Private' }}
    timeout-minutes: 30

    steps:
    - name: Get system specs
      run: lsb_release -a
    - name: Get other system specs
      run: uname -a

    - name: Clone Desktop repo
      uses: actions/checkout@v2

    - name: Setup node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.13.2'
    - name: Install global dependencies
      run: npm install -g yarn@1.22.10

    - name: Install xvfb
      run: sudo apt-get install xvfb

    - name: Cache Desktop node_modules
      id: cache-desktop-modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ hashFiles('package.json', 'yarn.lock', 'patches/**') }}

    - name: Install Desktop node_modules
      if: steps.cache-desktop-modules.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile

    - name: Build typescript
      run: yarn generate
    - name: Bundle
      run: yarn build:webpack

    - name: Run startup benchmarks
      run: |
        set -o pipefail
        xvfb-run --auto-servernum node ts/test-mock/benchmarks/startup_bench.js |
          tee benchmark-startup.log
      timeout-minutes: 10
      env:
        NODE_ENV: production
        RUN_COUNT: 10
        ELECTRON_ENABLE_STACK_DUMPING: on
        ARTIFACTS_DIR: artifacts/startup

    - name: Run send benchmarks
      run: |
        set -o pipefail
        rm -rf /tmp/mock
        xvfb-run --auto-servernum node ts/test-mock/benchmarks/send_bench.js |
          tee benchmark-send.log
      timeout-minutes: 10
      env:
        NODE_ENV: production
        RUN_COUNT: 100
        ELECTRON_ENABLE_STACK_DUMPING: on
        ARTIFACTS_DIR: artifacts/send

    - name: Run group send benchmarks
      run: |
        set -o pipefail
        rm -rf /tmp/mock
        xvfb-run --auto-servernum node \
          ts/test-mock/benchmarks/group_send_bench.js | \
          tee benchmark-group-send.log
      timeout-minutes: 10
      env:
        NODE_ENV: production
        RUN_COUNT: 100
        ELECTRON_ENABLE_STACK_DUMPING: on
        ARTIFACTS_DIR: artifacts/group-send

    - name: Run conversation open benchmarks
      run: |
        set -o pipefail
        rm -rf /tmp/mock
        xvfb-run --auto-servernum node \
          ts/test-mock/benchmarks/convo_open_bench.js | \
          tee benchmark-convo-open.log
      timeout-minutes: 10
      env:
        NODE_ENV: production
        RUN_COUNT: 100
        ELECTRON_ENABLE_STACK_DUMPING: on
        ARTIFACTS_DIR: artifacts/convo-open

    - name: Upload benchmark logs on failure
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: logs
        path: artifacts

    - name: Clone benchmark repo
      uses: actions/checkout@v2
      with:
        repository: 'signalapp/Signal-Desktop-Benchmarks-Private'
        path: 'benchmark-results'
        token: ${{ secrets.AUTOMATED_GITHUB_PAT }}

    - name: Push benchmark repo
      working-directory: benchmark-results
      run: |
        npm ci
        node ./bin/collect.js ../benchmark-startup.log data/startup.json
        node ./bin/collect.js ../benchmark-send.log data/send.json
        node ./bin/collect.js ../benchmark-group-send.log data/group-send.json
        node ./bin/collect.js ../benchmark-convo-open.log data/convo-open.json
        npm run build
        git config --global user.email "no-reply@signal.org"
        git config --global user.name "Signal Bot"
        git add .
        git commit --message "${GITHUB_REF} ${GITHUB_SHA}"
        git push --force origin main
